### ISSUE TITLE
need to add 'enhancer' step to predict pipeline and display the newdata provided in the mutations bar plot

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#157]
I added a new program that I call enhancer
Its python code that scans the json prediction output and the var file to identify additional mutations to provide to the user. the enhancer varMatchUnk.py adds two json dictionaries at the end. The first displays "new" mutations (not previously seen by our prediction algorithm. The second dictionary contains the lineage snps. These need to displayed in the bar plot in pink and blue respectively.

**Comment by mahafarhat** [comment]
I test it and the job is running within pipeline 2.0 (MP), however on the display end the website needs to process two new datastructures that will be available in the json file: Here is an example: the first three are normall present (1- prediction, 2-important mutations, 3-other mutations), the two new data structure are 4- New mutations (New) and 5- Lineage related polymorphisms (Lineage). The latter two should be displayed in pink and blue respectively. 


[
  [
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "inh", "0", "4.95", "8.76"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "rif", "0.999", "5.89", "4.89"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "pza", "0", "33.36", "7.76"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "emb", "0", "21.28", "16.64"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "str", "0.735", "37.94", "11.44"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "eth", "0", "40.31", "12.76"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "kan", "0.997", "32.95", "3.01"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "cap", "0.999", "61.07", "5.1"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "amk", "0.999", "16.71", "2.54"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "cip", "0", "44.68", "1.6"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "levo", "0", "26.48", "0.92"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "oflx", "0.003", "20.33", "11.53"],
    ["/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated", "pas", "0", "84.64", "0.7"]
  ],
  {
    "/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated": [
      [null, "SNP_CN_761155_C1349T_S450L_rpoB", null, null, "SNP_N_1473246_A1401G_rrs", null, "SNP_N_1473246_A1401G_rrs", "SNP_N_1473246_A1401G_rrs", "SNP_N_1473246_A1401G_rrs", null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null, null, null, null]
    ]
  },
  {
    "/n/groups/gentb_www/predictData/tbdata_00000329/Peru3428_annotated": [
      [null, null, null, "SNP_CN_4242803_G2941C_V981L_embC", "SNP_P_781395_T165C_promoter_rpsL", null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null, null, null, null]
    ]
  }
] 

{"0": ["DEL_CF_2155296_d816G_273_katG", "SNP_CN_761155_C1349T_S450L_rpoB", "Null", "SNP_CN_4248705_C2192T_P731L_embB", "SNP_P_781395_T165C_promoter-rpsL", "Null", "Null", "Null", "Null", "Null", "Null", "Null", "Null"]}

{"0": ["Null", "Null", "Null", "SNP_CN_4242803_G2941C_V981L_embC", "Null", "Null", "Null", "Null", "Null", "SNP_CN_7362_G61C_E21Q_gyrA", "SNP_CN_7362_G61C_E21Q_gyrA", "SNP_CN_7362_G61C_E21Q_gyrA", "Null"], "1": ["Null", "Null", "Null", "Null", "Null", "Null", "Null", "Null", "Null", "SNP_CN_7585_G284C_S95T_gyrA", "SNP_CN_7585_G284C_S95T_gyrA", "SNP_CN_7585_G284C_S95T_gyrA", "Null"], "2": ["Null", "Null", "Null", "Null", "Null", "Null", "Null", "Null", "Null", "SNP_CN_9304_G2003A_G668D_gyrA", "SNP_CN_9304_G2003A_G668D_gyrA", "SNP_CN_9304_G2003A_G668D_gyrA", "Null"]}

**Comment by doctormo** [comment]
Is the resulting json file a valid json file?

**Comment by mahafarhat** [comment]
Please suggest edits if it’s not and we can adjust the python code accordingly. 

Maha

**Comment by mahafarhat** [comment]
I think its officially not a valid json as the predict no longer displays anything even though the pipeline ran successfully

**Comment by mahafarhat** [comment]
![image](https://user-images.githubusercontent.com/8130645/59374938-08a25300-8d1b-11e9-884a-c7ecaa680ed3.png)

**Comment by doctormo** [comment]
I've pushed a fix to the repository, I've also used a program called `black` to clean up the python formatting (I'm actually amazed by the quality of the program, it really helped when editing this script).

Can you deploy the script again Maha and try again?

**Comment by mahafarhat** [comment]
did that and json file is now updated, but website still not able to display any results. Here is a link to the new json output:

https://gentb.hms.harvard.edu/tb/media/data/tbdata_00000330/Peru3428_matrix.json

**Comment by mahafarhat** [comment]
closing this!
